apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - port: 5672
      name: amqp
      targetPort: 5672
      nodePort: 30500
    - port: 15672
      name: management
      targetPort: 15672
      nodePort: 30501